/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        jakarta: ['Plus Jakarta Sans', 'sans-serif'],
        vietnam: ['Be Vietnam Pro', 'sans-serif'],
      },
      colors: {
        // EcoSync palette
        eco: {
          primary: '#006d32',
          'on-primary': '#ffffff',
          'primary-container': '#00d166',
          'on-primary-container': '#005324',
          'primary-fixed': '#64ff92',
          'on-primary-fixed': '#00210b',
          secondary: '#0059bb',
          'on-secondary': '#ffffff',
          'secondary-container': '#0070ea',
          'secondary-fixed': '#d8e2ff',
          'on-secondary-fixed': '#001a41',
          'on-secondary-fixed-variant': '#004493',
          tertiary: '#565e74',
          'on-tertiary': '#ffffff',
          error: '#ba1a1a',
          'on-error': '#ffffff',
          'error-container': '#ffdad6',
          'on-error-container': '#93000a',
          background: '#f8f9ff',
          'on-background': '#0b1c30',
          surface: '#f8f9ff',
          'on-surface': '#0b1c30',
          'surface-variant': '#d3e4fe',
          'on-surface-variant': '#3c4a3d',
          'surface-dim': '#cbdbf5',
          'surface-bright': '#f8f9ff',
          'surface-container-lowest': '#ffffff',
          'surface-container-low': '#eff4ff',
          'surface-container': '#e5eeff',
          'surface-container-high': '#dce9ff',
          'surface-container-highest': '#d3e4fe',
          outline: '#6c7b6c',
          'outline-variant': '#bbcbb9',
          'inverse-surface': '#213145',
          'inverse-on-surface': '#eaf1ff',
          'inverse-primary': '#30e375',
        },
        // Bloom palette
        bloom: {
          primary: '#a53c05',
          'on-primary': '#ffffff',
          'primary-container': '#ff7e47',
          'on-primary-container': '#692200',
          'primary-fixed': '#ffdbce',
          'on-primary-fixed': '#370e00',
          'on-primary-fixed-variant': '#7f2b00',
          secondary: '#00696b',
          'on-secondary': '#ffffff',
          'secondary-container': '#9beeef',
          'on-secondary-container': '#006e70',
          'secondary-fixed': '#9ef1f2',
          'on-secondary-fixed': '#002021',
          'on-secondary-fixed-variant': '#004f51',
          tertiary: '#775a00',
          'on-tertiary': '#ffffff',
          'tertiary-container': '#c99d19',
          'on-tertiary-container': '#493700',
          'tertiary-fixed': '#ffdf97',
          'tertiary-fixed-dim': '#f0c03f',
          error: '#ba1a1a',
          'on-error': '#ffffff',
          'error-container': '#ffdad6',
          'on-error-container': '#93000a',
          background: '#fbf9f1',
          'on-background': '#1b1c17',
          surface: '#fbf9f1',
          'on-surface': '#1b1c17',
          'surface-variant': '#e4e3db',
          'on-surface-variant': '#57423a',
          'surface-dim': '#dcdad2',
          'surface-bright': '#fbf9f1',
          'surface-container-lowest': '#ffffff',
          'surface-container-low': '#f5f4ec',
          'surface-container': '#f0eee6',
          'surface-container-high': '#eae8e0',
          'surface-container-highest': '#e4e3db',
          outline: '#8b7268',
          'outline-variant': '#dfc0b5',
          'inverse-surface': '#30312c',
          'inverse-on-surface': '#f3f1e9',
          'inverse-primary': '#ffb599',
        },
      },
      maxWidth: {
        'container-max': '1280px',
      },
      spacing: {
        'margin-mobile': '20px',
      },
      keyframes: {
        'fade-in-up': {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        grow: {
          '0%': { strokeDashoffset: '1000' },
          '100%': { strokeDashoffset: '0' },
        },
      },
      animation: {
        'fade-in-up': 'fade-in-up 0.4s ease-out forwards',
        grow: 'grow 2s ease-out forwards',
      },
    },
  },
  plugins: [],
};
